name: BUILD WAR STORE TOMCAT and BUILD DOCKER IMAGE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build WAR File
        run: mvn clean package

      - name: Build Docker Image
        run: docker build -t java-repo-project6-docker-image:latest .

      - name: Check Docker Image
        run: docker images

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-2

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 |
          docker login --username AWS --password-stdin public.ecr.aws   

      - name: Tag Docker Image
        run: |
          docker tag github-actions-ecr:latest \
          public.ecr.aws/u7t1z1q1/github-actions-ecr:latest
      
      - name: Push Docker Image to ECR Public
        run: |
          docker push public.ecr.aws/u7t1z1q1/github-actions-ecr:latest